version: "3.9"
services:
        mogno-db:
                image: mongo:latest
                container_name: mongo_node_1
                hostname: node1
                networks:
                        test-net:
                                ipv4_address: 172.44.0.2
                expose:
                        - 27017
                ports:
                        - "27017:27017"
                volumes:
                        - ./scripts:/scripts
        user-service:
                image: user-service:current
                container_name: user-service
                hostname: user-service
                networks:
                        test-net:
                                ipv4_address: 172.44.0.3
                expose:
                        - 8080
                ports:
                        - "8080:8080"
        order-service:
                image: order-service:current
                container_name: order-service
                hostname: order-service
                networks:
                        test-net:
                                ipv4_address: 172.44.0.4
                expose:
                        - 8080
                ports:
                        - "8081:8080"
        eureka-server:
                image: eureka-server:current
                container_name: eureka-server
                hostname: eureka-server
                networks:
                        test-net:
                                ipv4_address: 172.44.0.99
                expose:
                        - 8761
                ports:
                        - "8761:8761"
networks:
  test-net:
    ipam:
      driver: default
      config:
        - subnet: 172.44.0.0/24
