eureka:
  client:
    service-url:
      defaultZone: http://172.44.0.99:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**